# Generated by Django 2.0.3 on 2018-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(db_column='Tid')),
                ('uid', models.IntegerField(db_column='Uid')),
                ('date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'Blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('uid', models.IntegerField(db_column='Uid', primary_key=True, serialize=False)),
                ('uname', models.CharField(blank=True, db_column='Uname', max_length=20, null=True)),
                ('upass', models.CharField(blank=True, db_column='Upass', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Bloger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(db_column='Tid')),
                ('uid', models.IntegerField(db_column='Uid')),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
            ],
            options={
                'db_table': 'Comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gath',
            fields=[
                ('tid', models.IntegerField(db_column='Tid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Gath',
                'managed': False,
            },
        ),
    ]
