# Generated by Django 2.0.3 on 2018-04-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('aid', models.AutoField(db_column='Aid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Attention',
                'managed': False,
            },
        ),
    ]
