# Generated by Django 2.0.3 on 2018-04-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_attention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
