# Generated by Django 2.0.3 on 2018-04-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180402_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': False},
        ),
    ]
