# Generated by Django 2.0.3 on 2018-04-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180402_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.TextField(blank=True, db_column='Title', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tid',
            field=models.AutoField(db_column='Tid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='uid',
            field=models.ForeignKey(db_column='Uid', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Bloger'),
        ),
    ]
